### ISSUE TITLE
Cannot use CLI to crawl data

### ISSUE THREAD

**Issue by asakeaoyama** [karust/goCommonCrawl#4]
I had configure my environment for the project. Command:**"gogetcrawl -h"** be can executed successfully. However, when I enter **"docker run uranusq/gogetcrawl url *.tutorialspoint.com/* --ext pdf --limit 5"** or even **"gogetcrawl url *.tutorialspoint.com/* --limit 10 --sources wb -o ./urls.txt"**, as the tutorial, a error emerged, and the error was "zsh: no matches found: *.tutorialspoint.com/*"

By the way, I can run "docker-compose up" successfully. But if I configure the docker-compose.yaml file:crawler:service:command from **"file *.cia.gov/* --ext jpeg --dir /app -c -v -s wb"** to **"file *.cia.gov/* --ext jpeg --dir /app -c -v -s cc"**, the crawler couldn't get any data. I merely changed the parameter of the web archive sources from wb to cc.  I don't know whether my command is correct that cause this problem. thx

note: the asterisks in the commands above has vanished after I posted.

**Comment by karust** [comment]
Hi! Thanks for reporting the issue. 
1. I've tried to reproduce it. Seems like it's only related to `zsh` somehow, since it works fine elsewhere (e.g. `bash`, windows cmd…).
2. I've also tried running `file .cia.gov/ --ext jpeg --dir /app -c -v -s cc`. Seems like there is no data for this query in the Common Crawl archives :)

**Comment by gwillem** [comment]
ZSH errors when a wildcard character doesn't match anything locally, so you need to quote any `*` and `?` chars
